name: Check README

on: [push]



jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the code
      - name: Download my code
        uses: actions/checkout@v3
      
      # Step 2: Check if README exists
      - name: Look for README
        run: |
          if [ -f "README1.md" ]; then
            echo "✅ README1.md exists!"
          else
            echo "❌ No README1.md found"
          fi
      - name: create file
        run: |
          touch sample.txt
          ls
      - name: make a floder 
        run: |
          mkdir key
          ls
          echo ${{ secrets.password }}
  verify-readme:
    runs-on: ubuntu-latest 
    steps:
      - name: new job
        run: |
          pwd
          ls -al
          
          
         






